### PR TITLE
Move pss values under the global property

### PR DESCRIPTION
**Pull request by allanger**

### CODE REVIEW

**Comment by piontec** [comment]
No change in `values.yaml` itself?

**Review by piontec — APPROVED** [review]

**Comment by Gacko** [comment]
What exactly is this changing? IIUC the parentheses are catching nil references, but as `global.podSecurityStandards.enforced` is defined in the values, it will never be nil, as long as nobody actively sets `global` or any of the sub-keys to `null`.

**Comment by allanger** [comment]
I was just a bunch of automated pull requests, in this repo nothing is really changed, others were not using the `global` prefix, but I was editing a lot of projects at the same time.

**Comment by Gacko** [comment]
Ah, I get you! Thanks for explaining! 🙂

> but I think that it's still better to be protected from somebody setting something to null

Well, I'd basically agree with you if this was really an optional value and an optional resource. If one of the keys is accidentally set to `null`, the chart installation will not fail. And by default and from one's expectation this value should not be `null`, so debugging why this particular resources are missing might get a bit harder with those safeguards.

In this particular case I don't think it's a big deal. But elsewhere we are using conditions checking if a particular CRD is known to the API server and do not install the resource if it isn't. Some CRDs get installed during cluster creation and with some bad timing you end up installing an app A without some important resources because it depends on a CRD installed by app B and was not installed by the time of installing app A.

**Comment by allanger** [comment]
> Ah, I get you! Thanks for explaining! 🙂
> 
> > but I think that it's still better to be protected from somebody setting something to null
> 
> Well, I'd basically agree with you if this was really an optional value and an optional resource. If one of the keys is accidentally set to `null`, the chart installation will not fail. And by default and from one's expectation this value should not be `null`, so debugging why this particular resources are missing might get a bit harder with those safeguards.
> 
> In this particular case I don't think it's a big deal. But elsewhere we are using conditions checking if a particular CRD is known to the API server and do not install the resource if it isn't. Some CRDs get installed during cluster creation and with some bad timing you end up installing an app A without some important resources because it depends on a CRD installed by app B, which was not installed by the time of installing app A.

But it's not a CRD check, that the big difference, isn't it?  :)

**Comment by Gacko** [comment]
No it isn't. Just wanted to point out that such safeguards can hide other root causes...

**Pull request merged**
