### PR TITLE
Add seccomp profile

### PR DESCRIPTION
**Pull request by uvegla**
Towards: https://github.com/giantswarm/roadmap/issues/2120

### CODE REVIEW

**Comment by uvegla** [comment]
Deployed to WC to test, looks good.

**Comment by fiunchinho** [comment]
I tried deploying this app into a CAPI WC and I'm getting this error
```
message: 'pods "hello-world-app-599cdddcdd-" is forbidden: PodSecurityPolicy:
      unable to admit pod: [spec.volumes[0]: Invalid value: "projected": projected
      volumes are not allowed to be used pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
      Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/hello-world-app]:
      Forbidden: seccomp may not be set]'
```

How can I fix this @uvegla @Strigix ?

**Comment by fiunchinho** [comment]
I think default PSPs are different between CAPI and `vintage`.

I used

```
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/cluster: jose48
  name: jose48-hello-world-app
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: hello-world-app
  namespace: giantswarm
  version: v1.3.0
```

**Comment by uvegla** [comment]
Thank, I take a look to reproduce on a `goat` WC.

**Comment by uvegla** [comment]
With just the essential changes to make it work I managed to deploy on a fresh `grizzly` MC:

```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 1.0.0
    app.kubernetes.io/name: hello-world-app
    giantswarm.io/cluster: w9im2
  name: jose48-hello-world-app
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  kubeConfig:
    context:
      name: w9im2
    inCluster: false
    secret:
      name: w9im2-kubeconfig
      namespace: org-giantswarm
  name: hello-world-app
  namespace: giantswarm
  version: v1.3.0
```

Also tried another one from `happa` and it works as well.

**Comment by fiunchinho** [comment]
In my case it was a WC, maybe that's the difference.

**Pull request merged**
